### ISSUE TITLE
instuctor button should be "After triggering Elemental Reaction"

### ISSUE THREAD

**Issue by MrPillow1** [frzyc/genshin-optimizer#956] opened 2023-02-06 23:32 UTC
![image](https://user-images.githubusercontent.com/91567263/217110759-71078a68-5ca6-4fe1-b164-1e76900b23c2.png)

**Comment by nguyentvan7** [comment] 2023-02-06 23:37
Dupe of #937, thank you though!

**Closed by nguyentvan7** 2023-02-06 23:37 UTC
