### ISSUE TITLE
Allow characters to be created from the "add to team" popup UI

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1540] opened 2024-02-25 07:35 UTC
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/bed9cda5-720b-49b2-9b29-4e39adcfd884)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/a4c6cbfd-9e04-4082-8123-b41aca1a6d2f)

**Comment by frzyc** [comment] 2024-02-25 08:11
Duplicate of https://github.com/frzyc/genshin-optimizer/issues/1521

**Closed by frzyc** 2024-02-25 08:11 UTC
