### ISSUE TITLE
Bug: Swapping a teammate's weapon does not update the weapon's conditional within teambuffs

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#552] opened 2022-08-07 07:58 UTC
Example: Enable Thrilling Tales conditional within teambuffs. Swap Thrilling Tales holder to a different weapon and then return to the previous character's teambuffs page and Thrilling Tales conditional will still appear until the page is refreshed.

https://cdn.discordapp.com/attachments/787340960173391903/1005744922978164766/2022-08-07_00-20-06-379.mp4

**Comment by StainAE86** [comment] 2022-08-07 10:18
Seems to also be the case when changing artifacts

![image](https://user-images.githubusercontent.com/101696552/183286182-4fb82851-bbae-4c3c-87e3-53859f8586d4.png)

**Comment by nguyentvan7** [comment] 2022-08-07 16:18
Possibly related to/dupe of #539?

**Comment by nguyentvan7** [comment] 2022-08-09 05:28
Closing as dupe of #539

**Closed by nguyentvan7** 2022-08-09 05:28 UTC
Labels: bug
