### ISSUE TITLE
Items missing in translation

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#1100] opened 2023-03-24 09:16 UTC
Some items are missing in languages other than EN, e.g., Basic Stats and Transformative Reactions:

![图片](https://user-images.githubusercontent.com/32670075/227475346-cd0c201f-53dc-4199-a11c-beac6d9fa76b.png)

And some weapons & artifacts:

![图片](https://user-images.githubusercontent.com/32670075/227475521-1fb84cf0-202f-4992-832f-39c5d5c7f0ac.png)

They are also missing in other languages, and are not in `libs/localization/assets/locales` or POEditor. So I'm assuming these strings should be added to locales.

**Comment by nguyentvan7** [comment] 2023-03-24 15:22
Dupe of #743

**Closed by nguyentvan7** 2023-03-24 15:22 UTC
