### ISSUE TITLE
Disallow Deepwood Memories set bonus stacking

### ISSUE THREAD

**Issue by Fizzy158** [frzyc/genshin-optimizer#2358] opened 2024-08-05 00:25 UTC
I have 2 characters with this artifact set on in a team. It says that I would get -60% Dendro Res Shred when in fact you cannot do that in game (at least to my knowledge)
![image](https://github.com/user-attachments/assets/ee9c26a5-a615-45fb-b61a-1069f43cda52)

**Comment by nguyentvan7** [comment] 2024-08-05 00:29
Dupe of #361

**Closed by nguyentvan7** 2024-08-05 00:29 UTC
