### ISSUE TITLE
ATK Buffs from "Elegy for the end" and "Freedom-Sworm" are merged.

### ISSUE THREAD

**Issue by gendoh** [frzyc/genshin-optimizer#685] opened 2022-10-12 03:36 UTC
In weapons' description,
> Of the many effects of the "Millennial Movement," buffs of the same type will not stack.

As I know, they are merged for different type, but for same type, max value is overriding others.

For this case :
![image](https://user-images.githubusercontent.com/2393477/195243485-ee7dbd57-b72b-40b3-ae1b-1135e24c2797.png)
not 70%, but 40% from Freedom-sworm is right value.

**Comment by nguyentvan7** [comment] 2022-10-12 04:42
Dupe of #361

**Closed by nguyentvan7** 2022-10-12 04:42 UTC
