### ISSUE TITLE
Artifact filter visually overflows

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#925] opened 2023-01-30 05:03 UTC
![image](https://user-images.githubusercontent.com/36019388/215391649-10028fe2-1dbc-4977-9920-b4e92a32073d.png)
Probably because it is a lot of artifacts + smaller screen

**Comment by frzyc** [comment] 2023-01-31 01:31
Duplicate of #917

**Closed by frzyc** 2023-01-31 01:31 UTC
