### ISSUE TITLE
Deepwood stacks Dendro RES Shred

### ISSUE THREAD

**Issue by Priwinn** [frzyc/genshin-optimizer#1369] opened 2023-12-14 14:01 UTC
I was checking wether Nahida is better with Golden Troupe when another team mate uses Deepwood and realized that the optimizer is stacking the deepwood RES Shred, so it is overestimating DMG for Nahida Deepwood when carrying another teammate with Deepwood 
![image](https://github.com/frzyc/genshin-optimizer/assets/43821596/0aa5b90a-b835-492a-9a50-c3fef9fb865f)

**Comment by nguyentvan7** [comment] 2023-12-14 14:38
dupe of #361. For now, just make sure to only enable one of them

**Closed by nguyentvan7** 2023-12-14 14:38 UTC
