### ISSUE TITLE
Add db import info for team/loadout/build

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2145] opened 2024-05-17 16:54 UTC
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/0a5fb085-a3be-4322-a7da-c992cac9a439)
Currently only shows art/weapon/char

For importing GO data on another GO data for team/loadout, I believe the current logic is the import data overwrite the existing data. I think I am fine with that, deduping would be unnecessarily complicated, the UI should just reflect this.

**Comment by CordonZeus22** [comment] 2024-05-17 19:05
I will work on it

**Comment by CordonZeus22** [comment] 2024-05-17 21:57
Actually, importing teams doesn't remove existing teams not in import. Even with the `Delete items not in import` option. Same for loadout. Is this behavior intended ?

**Comment by nguyentvan7** [comment] 2024-05-17 22:03
Seems so https://discord.com/channels/785153694478893126/1218906581593231540, tho i still feel like its weird that teams are not deleted with that setting enabled

**Comment by CordonZeus22** [comment] 2024-05-17 22:16
This thread has been marked as not a bug. So, this behavior shouldn't be changed ?

**Comment by nguyentvan7** [comment] 2024-05-17 22:17
Leaving @frzyc to give final say

**Comment by frzyc** [comment] 2024-05-18 02:58
> For importing GO data on another GO data for team/loadout, I believe the current logic is the import data overwrite the existing data. I think I am fine with that, deduping would be unnecessarily complicated, the UI should just reflect this.

Yeah i do not think its worth any developer's time to dedup/merge team/loadouts. The ask for this issue is basically just add a tally as a visual for users, and not to add any complex logic to db

**Comment by CordonZeus22** [comment] 2024-05-18 21:07
There is already a dedup/merge for team and loadouts I think

**Comment by CordonZeus22** [comment] 2024-05-21 20:47
If no dedup/merge should be done, what will be written on the card ?

**Comment by frzyc** [comment] 2024-05-21 21:53
Yes, and TC builds

**Comment by CordonZeus22** [comment] 2024-05-23 21:49
How the total amout of loadouts can be computed ?

**Comment by frzyc** [comment] 2024-05-23 22:49
yeah loadouts are called `teamChars`(due to legacy naming) so it would be `database.teamChars.values.length`

**Comment by CordonZeus22** [comment] 2024-05-23 22:51
Thanks

**Closed** 2024-05-28 03:47 UTC
