### ISSUE TITLE
Unable to rename a loadout if it doesn't exist within a team

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1689] opened 2024-03-13 14:21 UTC
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/e9c239b1-6186-4a8f-866d-f39b3679bf6f)

**Comment by frzyc** [comment] 2024-03-14 02:15
Duplicate of https://github.com/frzyc/genshin-optimizer/issues/1684

**Closed by frzyc** 2024-03-14 02:15 UTC
Labels: enhancement, teams
