### ISSUE TITLE
Add team and self buffs to multi target configuration as bonus stats

### ISSUE THREAD

**Issue by SpaceSlash** [frzyc/genshin-optimizer#2168] opened 2024-05-22 12:38 UTC
Problem: Some team buff expire halfway through rotation so setting them in team settings creates misleading results; for example in International Childe's Burst and first 2 N3C are buffed by Bennett Burst but 2 N2C after that are not.
OR
Some characters have dynamic buffs, such as: Arclecchino Bond of Life, Furina Fanfare, Neuvillette A4 Passive etc.

Solution: Add team and self buffs as bonus stats in multi target configuration that can be added to each target individually.

**Comment by nguyentvan7** [comment] 2024-05-22 14:21
Dupe of #904

**Closed by nguyentvan7** 2024-05-22 14:21 UTC
