### ISSUE TITLE
Add placeholder characters to the team editor

### ISSUE THREAD

**Issue by BrandonXLF** [frzyc/genshin-optimizer#1764] opened 2024-03-17 03:49 UTC
It would be nice to have a placeholder character that can be added to teams to enable elemental resonances without selecting specific characters. The placeholder "character" should be able to be added multiple times and should have the option to set what element they are, if known.

![image](https://github.com/frzyc/genshin-optimizer/assets/42590338/5f7b9049-d39f-47d8-a78f-7f2d5dcde468)

**Comment by nguyentvan7** [comment] 2024-03-17 04:50
Dupe of #1242

**Closed by nguyentvan7** 2024-03-17 04:50 UTC

**Comment by frzyc** [comment] 2024-03-17 07:17
Adding a "random character of element" is a lot faster than us coding in a placeholder in this system.
