### ISSUE TITLE
Changing character talent drop downs cause page to freeze

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#936] opened 2023-02-03 09:32 UTC
Only on the talent page, not on team-mate talent drop downs.

Seems to be isolated to my database as far as I can tell - but can reproduce it in Chrome and Edge using my database.

Steps:
Go to Raiden
Change her resolve stacks to something else

Also failing on Yoimiya changing her A1 passive dropdown

Interestingly doesnt happen for Yelan's A4

[Stain_2023-02-03_09-25-32.txt](https://github.com/frzyc/genshin-optimizer/files/10577510/Stain_2023-02-03_09-25-32.txt)

**Comment by StainAE86** [comment] 2023-02-03 09:43
Inspecting the page after its frozen:

![image](https://user-images.githubusercontent.com/101696552/216567034-082c758a-fffb-499a-a26f-e42f4d8b3da4.png)

**Comment by frzyc** [comment] 2023-02-03 09:49
I'm having trouble reproducing this issue. It looks like the dropdown `presentation` overlay is stuck even after selection an option, disallowing you to interact with the elements under the overlay.

**Comment by StainAE86** [comment] 2023-02-03 10:20
After deleting Raiden from my database and recreating her it's increasingly difficult to recreate this issue on my end now.
It seems to sometimes work, sometimes not. Once it fails it will fail every time until some other condition is changed (artifact swap, weapon passive toggle, talent level, etc) and then it will begin to work again until the next failure.

Can't find a way to reliably reproduce it anymore.

**Comment by nguyentvan7** [comment] 2023-02-03 15:22
I was also experiencing this when I was trying to fix the initial dropdown bug. Every instance of MenuItem was completely borked and having this issue, which explains why I thought the separation of tooltip from the dropdown wasn't working as a fix

**Comment by frzyc** [comment] 2023-02-03 21:09
@nguyentvan7 can you still produce it? I've not been able to reproduce even once

**Comment by nguyentvan7** [comment] 2023-02-03 21:12
Nope and when i was able to reproduce it, I wasnt able to fix it with code changes either

**Comment by nguyentvan7** [comment] 2023-02-03 21:12
Possibly another occurrence of the bug

![image](https://user-images.githubusercontent.com/36019388/216711670-a788f6b8-3d0c-49f7-b7f1-273b5a912fe8.png)

**Comment by nguyentvan7** [comment] 2023-02-03 21:14
Possibly https://github.com/mui/material-ui/issues/32286 ?

**Comment by StainAE86** [comment] 2023-02-04 03:43
I think I've figured out what was causing this and why you cant reproduce it with my database.

My Raiden and Yoimiya (but not Yelan) had a TC Tab build set. TC Tab builds arent saved in the json, but still in the local storage.
And even if you "delete" the database before uploading a new database, the TC Tab retains whatever TC build used to be there.

Once I cleared the TC build the page no longer freezes. (Obviously deleting Raiden and re-creating her also cleared the TC Tab)

**Comment by frzyc** [comment] 2023-02-04 06:07
what was in the TC tab locally that was causing the freeze? I've tried a few things with TC builds and I still can't replicate

**Comment by StainAE86** [comment] 2023-02-04 06:32
I just copied from equipped and then made some random changes. different weapon, different main stat, different set for example

**Comment by frzyc** [comment] 2023-02-04 07:58
can you give as exact reproduction step as possible? I am unable to replicate

**Comment by StainAE86** [comment] 2023-02-04 08:27
i think im barking up the wrong tree again. because  when trying to make a step by step recreation of it now it's still inconsistent for me.

What I have found is that it is the same issue as the artifact assume main stat level drop down bug.
The dropdown is still there, hidden, but selectable which clears the frozen page fault.

![image](https://user-images.githubusercontent.com/101696552/216757241-542543e8-4ed6-4e93-93ef-8625a0ecab74.png)

However now I'm thinking it's occuring due to an accidental rapid double click when selecting something from the dropdown.

**Comment by frzyc** [comment] 2023-02-04 09:07
Oh, I can reproduce by double clicking the menu element. your mouse probably has a double click issue: https://codepen.io/blink172/pen/vERyxK

**Comment by StainAE86** [comment] 2023-02-04 09:30
![image](https://user-images.githubusercontent.com/101696552/216759742-b922cace-5a28-417e-a6ee-992726113202.png)

Maybe, but I'd expect to see some miss clicks here if that was the case.

My assumption is its linked to the same issue in 2nd paragraph of #907 

Maybe that should have been its own issue - as that bug still isnt fixed

**Comment by nguyentvan7** [comment] 2023-02-04 16:49
Second part of #907 will be fixed in #853

**Comment by nguyentvan7** [comment] 2023-02-04 16:53
My bet is it's still the race condition in the other post I linked, and certain things can aggravate it to appear more often, like tooltip or double clicks or long render cycles

**Comment by StainAE86** [comment] 2023-02-04 23:06
Yep that matches up to what I'm seeing. The "laggier" the UI is due to more characters/conditionals/multi-targets/etc that need to be recaluclated when changing the drop down, the wider the window is for the dropdown to be inturrupted by an double click.

So this is probably more prominent on less powerful machines and could explain why it's harder to reproduce for some

**Comment by Sinesthesia** [comment] 2023-02-06 05:10
> So this is probably more prominent on less powerful machines

Can confirm this, at least. Hyperbloom stuff I was testing: Overview and team buffs tab, Key dropdown froze the page. Talents tab, Yelan's a4.

While the game is running the drop-downs broke 100%. Close the game to free resources and they work fine.

**Comment by nguyentvan7** [comment] 2023-02-06 05:11
Well seems like we either wait for this race condition fix, or convert everything to autocomplete, which avoids this issue by not creating a full screen overlay, and not fixing the screen completely when the dropdown is open

**Closed** 2023-02-11 10:32 UTC
Labels: bug
