### ISSUE TITLE
Add popup to weapon deletion listing which builds this will affect

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#1785] opened 2024-03-18 21:04 UTC
Add popup to weapon deletion listing which builds this will affect (not this PR)

_Originally posted by @nguyentvan7 in https://github.com/frzyc/genshin-optimizer/pull/1777#pullrequestreview-1944183784_

**Comment by nguyentvan7** [comment] 2024-03-18 21:05
dupe of #1784

**Closed by nguyentvan7** 2024-03-18 21:05 UTC
