### ISSUE TITLE
Bug: DMG bonus on character preview card not in-line with other stats

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#550] opened 2022-08-06 22:12 UTC
![image](https://user-images.githubusercontent.com/101696552/183267555-2f70c64b-0fba-4840-a528-1d832c8e54e2.png)

![reee](https://user-images.githubusercontent.com/101696552/183267572-b30e812f-5a28-4a67-b9ea-36c915106e09.gif)

**Comment by frzyc** [comment] 2022-08-07 03:03
Hmmmm, this is working as intended. "WONT FIX" 
![giphy](https://user-images.githubusercontent.com/1754901/183273141-38fa37a0-c5e1-4cec-9e8f-9587a0479cda.gif)

**Closed** 2022-08-11 21:27 UTC
Labels: bug
