### ISSUE TITLE
Move Amber C1 into its own box

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#585] opened 2022-08-29 07:29 UTC
![image](https://user-images.githubusercontent.com/101696552/187147411-de917f05-2c62-4a32-8e7a-1049135bb58a.png)

**Comment by nguyentvan7** [comment] 2022-09-04 07:11
More of a dupe of #523 IMO

**Closed by nguyentvan7** 2022-09-04 07:11 UTC
Labels: enhancement
