### ISSUE TITLE
Certain artifact sets stack when they shouldn't

### ISSUE THREAD

**Issue by iwantcookiesnow** [frzyc/genshin-optimizer#2247] opened 2024-06-16 21:53 UTC
Hello, I noticed that certain artifact sets will duplicate their effects in the optimizer when multiple characters with that set are in the same team, examples are Deepwood Memories and Viridescent Venerer. The optimizer assumes that, since two characters with e.g. Deepwood are in the team, the 30% bonus is doubled to 60%.

![image](https://github.com/frzyc/genshin-optimizer/assets/74122765/6e35c434-9383-4577-afad-7669c479a76c)
![image](https://github.com/frzyc/genshin-optimizer/assets/74122765/808c0381-f628-4b93-bfbd-7849c06595c9)

**Comment by nguyentvan7** [comment] 2024-06-16 21:57
Dupe of #361

**Closed** 2024-06-16 22:11 UTC
